version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: mypassword
    port: 5432
    # ports:
    #   - "5432:5432"
    listen_addresses : '*'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  django_app:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Django Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./companyapi:/app  # Mount the project directory as a volume
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
