# Generated by Django 4.2.10 on 2024-04-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
