# Generated by Django 4.2.10 on 2024-04-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='email',
            name='to',
            field=models.EmailField(max_length=254),
        ),
    ]
